apiVersion: apps/v1
kind: Deployment
metadata:
  name: omniops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omniops
  template:
    metadata:
      labels:
        app: omniops
    spec:
      containers:
        - name: omniops-app
          image: karandeven/omniops-app:latest
          imagePullPolicy: Always
          env:
            - name: APP_NAME
              value: "OMNIOPS"
            - name: ENV
              value: "production"
          ports:
            - containerPort: 80

